import type express from 'express';
import { folderShareService } from '../../services/folder-share-service.js';
import { postShareService, type PostShareGrant } from '../../services/post-share-service.js';
import { galleryService } from '../../services/gallery-service.js';
import { requireCapability } from '../../middleware/auth-protection.js';
import { createRateLimiter } from '../../middleware/rate-limit.js';
import { createVideoStreamRouter } from '../../routes/video-stream.js';
import { serveDerivativeForImage } from '../../routes/lazy-derivatives.js';
import { applyNoStoreMediaHeaders } from '../../utils/media-response.js';
import { appSettingsRepository } from '../../db/repositories.js';
import { SHARE_PUBLIC_BASE_URL_SETTING_KEY } from '../../constants/app-setting-keys.js';
import { normalizePublicBaseUrl, resolveShareBaseUrl } from '../../utils/share-url.js';
import { authService } from '../../services/auth-service.js';
import { createShareLinkBodySchema, imageIdSchema, mediaTypeQuerySchema, paginationQuerySchema, shareLinkIdSchema, sharePasswordBodySchema, shareTokenBodySchema, shareTokenParamSchema, slugSchema, submittedSharePasswordBodySchema } from '../../routes/api-schemas.js';

const unlockLimiter = createRateLimiter({ windowMs: 60 * 1000, max: 20, message: 'Too many share unlock attempts. Please try again in a minute.' });
const POST_SHARE_GRANTS = new WeakMap<express.Request, PostShareGrant>();
function setHeaders(response: express.Response): void { response.setHeader('Cache-Control', 'private, no-store'); response.vary('Cookie'); }
function deny(response: express.Response, status = 401): void { setHeaders(response); response.status(status).json({ message: 'This folder share is expired, revoked, or locked.' }); }
function denyPost(response: express.Response): void { setHeaders(response); response.status(404).json({ message: 'This share link is expired, revoked, or invalid.' }); }
function ensure(request: express.Request, response: express.Response, folderId: number): boolean { if (!folderShareService.getFolderGrant(request, folderId)) { deny(response); return false; } setHeaders(response); return true; }
function expiration(body: ReturnType<typeof createShareLinkBodySchema.parse>): Date | null { if (body.unlimited || body.expiresIn === 'unlimited') return null; if (body.expiresIn === 'custom') return new Date(body.customExpiresAt as string); return new Date(Date.now() + (body.expiresIn === '1h' ? 3600000 : body.expiresIn === '7d' ? 604800000 : 86400000)); }
function grant(request: express.Request): PostShareGrant | null { const cached = POST_SHARE_GRANTS.get(request); if (cached) return cached; const parsed = shareTokenParamSchema.safeParse(request.params); if (!parsed.success) return null; const value = postShareService.verifyToken(parsed.data.token, { touch: true }); if (value) POST_SHARE_GRANTS.set(request, value); return value; }
function publicBase(): string | null { return normalizePublicBaseUrl(appSettingsRepository.get(SHARE_PUBLIC_BASE_URL_SETTING_KEY)); }
function postUrl(request: express.Request, token: string): string { const suffix = `/s/${encodeURIComponent(token)}`; const base = resolveShareBaseUrl({ forwardedHost: request.get('x-forwarded-host'), forwardedProto: request.get('x-forwarded-proto'), host: request.get('host'), secure: request.secure }, publicBase()); return base ? `${base}${suffix}` : suffix; }

export function registerFolderSharingAdminRoutes(router: express.Router): void {
  const manage = requireCapability('canManageLibrary', 'Admin access is required.');
  router.get('/admin/folders/:slug/share-links', manage, (request, response) => { const params = slugSchema.parse(request.params); const payload = folderShareService.listLinks(params.slug); if (!payload) { response.status(404).json({ message: 'Folder not found' }); return; } response.json({ links: payload.links, password: payload.password, publicFolderUrl: `/folders/${encodeURIComponent(payload.folder.slug)}`, publicAccess: !authService.isEnabled() || authService.isPublicViewerAccessEnabled() }); });
  router.post('/admin/folders/:slug/share-links', manage, (request, response) => { const params = slugSchema.parse(request.params); const body = createShareLinkBodySchema.parse(request.body); const created = folderShareService.createLink(params.slug, { expiresAt: expiration(body) }); if (!created) { response.status(404).json({ message: 'Folder not found' }); return; } response.status(201).json({ ok: true, shareUrl: `/share/${encodeURIComponent(created.folder.slug)}#token=${encodeURIComponent(created.rawToken)}`, link: created.link }); });
  router.delete('/admin/folders/:slug/share-links/:linkId', manage, (request, response) => { const params = slugSchema.merge(shareLinkIdSchema).parse(request.params); const link = folderShareService.revokeLink(params.slug, params.linkId); if (!link) { response.status(404).json({ message: 'Share link not found' }); return; } response.json({ ok: true, link }); });
  router.put('/admin/folders/:slug/share-password', manage, (request, response) => { const params = slugSchema.parse(request.params); const body = sharePasswordBodySchema.parse(request.body); const password = folderShareService.setPassword(params.slug, body.password); if (!password) { response.status(404).json({ message: 'Folder not found' }); return; } response.json({ ok: true, password: { enabled: password.enabled, updatedAt: password.updatedAt } }); });
  router.delete('/admin/folders/:slug/share-password', manage, (request, response) => { const params = slugSchema.parse(request.params); const password = folderShareService.removePassword(params.slug); if (!password) { response.status(404).json({ message: 'Folder not found' }); return; } response.json({ ok: true, password: { enabled: false, updatedAt: null } }); });
}

export function registerFolderSharingPublicRoutes(router: express.Router): void {
  router.get('/share/folders/:slug/access', (request, response) => { const params = slugSchema.parse(request.params); const access = folderShareService.getAccessState(request, params.slug); if (!access.exists) { response.status(404).json({ message: 'Folder share not found' }); return; } setHeaders(response); response.json(access); });
  router.post('/share/folders/:slug/unlock-link', unlockLimiter, (request, response) => { const params = slugSchema.parse(request.params); const body = shareTokenBodySchema.parse(request.body); const value = folderShareService.verifyLinkToken(params.slug, body.token); if (!value) { folderShareService.clearShareSession(response, request); deny(response, 403); return; } folderShareService.setShareSession(response, request, value); setHeaders(response); response.json({ ok: true }); });
  router.post('/share/folders/:slug/unlock-password', unlockLimiter, (request, response) => { const params = slugSchema.parse(request.params); const body = submittedSharePasswordBodySchema.parse(request.body); const value = folderShareService.verifyPassword(params.slug, body.password); if (!value) { folderShareService.clearShareSession(response, request); deny(response); return; } folderShareService.setShareSession(response, request, value); setHeaders(response); response.json({ ok: true }); });
  router.get('/share/folders/:slug', (request, response) => { const params = slugSchema.parse(request.params); const folder = galleryService.getSharedFolderBySlug(params.slug); if (!folder) { response.status(404).json({ message: 'Folder share not found' }); return; } if (ensure(request, response, folder.id)) response.json(folder); });
  router.get('/share/folders/:slug/images', (request, response) => { const params = slugSchema.parse(request.params); const query = paginationQuerySchema.merge(mediaTypeQuerySchema).parse(request.query); const payload = galleryService.getSharedFolderImages(params.slug, query.page, query.limit, query.mediaType); if (!payload) { response.status(404).json({ message: 'Folder share not found' }); return; } if (ensure(request, response, payload.folder.id)) response.json(payload); });
  registerSharedDetail(router, '/share/images/:id', true); registerSharedDetail(router, '/share/posts/:id', false);
}
function registerSharedDetail(router: express.Router, path: string, legacy: boolean): void { router.get(path, (request, response) => { const params = imageIdSchema.parse(request.params); const query = mediaTypeQuerySchema.parse(request.query); const image = galleryService.getSharedImageDetail(params.id, query.mediaType, { isLegacyImageAlias: legacy }); if (!image) { response.status(404).json({ message: 'Post not found' }); return; } if (ensure(request, response, image.folderId)) response.json(image); }); }

export function registerPostSharingRoutes(router: express.Router): void {
  const manage = requireCapability('canManageLibrary', 'Admin access is required.');
  router.get('/share/posts/:id/links', manage, (request, response) => { const params = imageIdSchema.parse(request.params); const payload = postShareService.listLinks(params.id); if (!payload) { response.status(404).json({ message: 'Post not found' }); return; } response.json({ links: payload.links, publicBaseUrl: publicBase() }); });
  router.post('/share/posts/:id', manage, (request, response) => { const params = imageIdSchema.parse(request.params); const body = createShareLinkBodySchema.parse(request.body ?? {}); const created = postShareService.createLink(params.id, { expiresAt: expiration(body) }); if (!created) { response.status(404).json({ message: 'Post not found' }); return; } response.status(201).json({ ok: true, link: created.link, shareUrl: postUrl(request, created.rawToken), sharePath: `/s/${encodeURIComponent(created.rawToken)}` }); });
  router.delete('/share/posts/:id/links/:linkId', manage, (request, response) => { const params = imageIdSchema.merge(shareLinkIdSchema).parse(request.params); const link = postShareService.revokeLink(params.id, params.linkId); if (!link) { response.status(404).json({ message: 'Share link not found' }); return; } response.json({ ok: true, link }); });
  router.get('/share/post-links/:token', (request, response) => { const value = grant(request); if (!value) { denyPost(response); return; } const params = shareTokenParamSchema.parse(request.params); const detail = galleryService.getTokenSharedPostDetail(value.postId, `/api/share/post-links/${encodeURIComponent(params.token)}/images`, `/api/share/post-links/${encodeURIComponent(params.token)}/videos`); if (!detail) { denyPost(response); return; } setHeaders(response); response.json(detail); });
  router.get('/share/post-links/:token/images/:id/thumbnail', async (request, response) => { const value = grant(request); const params = imageIdSchema.parse(request.params); if (!value || !postShareService.grantCoversImage(value, params.id)) { denyPost(response); return; } const image = galleryService.getShareDerivativeImage(params.id); if (!image) { response.status(404).json({ message: 'Thumbnail not found' }); return; } setHeaders(response); await serveDerivativeForImage(response, image, 'thumbnail', { noStore: true }); });
  router.get('/share/post-links/:token/images/:id/preview', async (request, response) => { const value = grant(request); const params = imageIdSchema.parse(request.params); if (!value || !postShareService.grantCoversImage(value, params.id)) { denyPost(response); return; } const image = galleryService.getShareDerivativeImage(params.id); if (!image) { response.status(404).json({ message: 'Preview not found' }); return; } setHeaders(response); if (image.media_type === 'video') { const original = galleryService.getOriginalMediaFile(image.id); if (!original) { response.status(404).json({ message: 'Preview not found' }); return; } applyNoStoreMediaHeaders(response); response.sendFile(original.path); return; } await serveDerivativeForImage(response, image, 'preview', { noStore: true }); });
  router.use('/share/post-links/:token/videos', createVideoStreamRouter({ authorizeImage: (request, imageId) => { const value = grant(request); return Boolean(value && postShareService.grantCoversImage(value, imageId)); }, buildPlaylistPath: (request, imageId, quality) => { const token = String((request.params as { token?: string }).token ?? ''); return `/api/share/post-links/${encodeURIComponent(token)}/videos/${imageId}/hls/${quality}/index.m3u8`; } }));
  router.get('/share/images/:id/thumbnail', async (request, response) => { const params = imageIdSchema.parse(request.params); const image = galleryService.getShareDerivativeImage(params.id); if (!image) { response.status(404).json({ message: 'Thumbnail not found' }); return; } if (ensure(request, response, image.folder_id)) await serveDerivativeForImage(response, image, 'thumbnail', { noStore: true }); });
  router.get('/share/images/:id/preview', async (request, response) => { const params = imageIdSchema.parse(request.params); const image = galleryService.getShareDerivativeImage(params.id); if (!image) { response.status(404).json({ message: 'Preview not found' }); return; } if (!ensure(request, response, image.folder_id)) return; if (image.media_type === 'video') { const original = galleryService.getOriginalMediaFile(image.id); if (!original) { response.status(404).json({ message: 'Preview not found' }); return; } applyNoStoreMediaHeaders(response); response.sendFile(original.path); return; } await serveDerivativeForImage(response, image, 'preview', { noStore: true }); });
}
