import { feedGalleryMethods } from './gallery-service/feed.js';
import { foldersGalleryMethods } from './gallery-service/folders.js';
import { sharesGalleryMethods } from './gallery-service/shares.js';
import { placesGalleryMethods } from './gallery-service/places.js';
import { collectionsGalleryMethods } from './gallery-service/collections.js';
import { interactionsGalleryMethods } from './gallery-service/interactions.js';
import { adminGalleryMethods } from './gallery-service/admin.js';

export const galleryService = {
  getFeed: feedGalleryMethods.getFeed,
  getReels: feedGalleryMethods.getReels,
  searchMedia: feedGalleryMethods.searchMedia,
  listMoments: feedGalleryMethods.listMoments,
  getMomentFeed: feedGalleryMethods.getMomentFeed,
  listFolders: foldersGalleryMethods.listFolders,
  listPlaces: placesGalleryMethods.listPlaces,
  getPlaceBySlug: placesGalleryMethods.getPlaceBySlug,
  getPlaceImages: placesGalleryMethods.getPlaceImages,
  getFolderBySlug: foldersGalleryMethods.getFolderBySlug,
  getSharedFolderBySlug: sharesGalleryMethods.getSharedFolderBySlug,
  updateFolderMetadata: foldersGalleryMethods.updateFolderMetadata,
  updateImageCaption: foldersGalleryMethods.updateImageCaption,
  setFolderAvatar: foldersGalleryMethods.setFolderAvatar,
  getFolderStories: foldersGalleryMethods.getFolderStories,
  getFolderStoryFeed: foldersGalleryMethods.getFolderStoryFeed,
  getFolderImages: foldersGalleryMethods.getFolderImages,
  getSharedFolderImages: sharesGalleryMethods.getSharedFolderImages,
  getImageDetail: foldersGalleryMethods.getImageDetail,
  getSharedImageDetail: sharesGalleryMethods.getSharedImageDetail,
  getTokenSharedPostDetail: sharesGalleryMethods.getTokenSharedPostDetail,
  getShareDerivativeImage: sharesGalleryMethods.getShareDerivativeImage,
  getPlacesStatus: placesGalleryMethods.getPlacesStatus,
  preparePlacesGeodata: placesGalleryMethods.preparePlacesGeodata,
  rebuildPlaces: placesGalleryMethods.rebuildPlaces,
  getTrashImages: interactionsGalleryMethods.getTrashImages,
  getCollections: collectionsGalleryMethods.getCollections,
  getCollectionImages: collectionsGalleryMethods.getCollectionImages,
  getImageCollections: collectionsGalleryMethods.getImageCollections,
  createCollection: collectionsGalleryMethods.createCollection,
  updateCollection: collectionsGalleryMethods.updateCollection,
  deleteCollection: collectionsGalleryMethods.deleteCollection,
  saveImage: collectionsGalleryMethods.saveImage,
  unsaveImage: collectionsGalleryMethods.unsaveImage,
  addImageToCollection: collectionsGalleryMethods.addImageToCollection,
  removeImageFromCollection: collectionsGalleryMethods.removeImageFromCollection,
  getLikes: interactionsGalleryMethods.getLikes,
  likeImage: interactionsGalleryMethods.likeImage,
  unlikeImage: interactionsGalleryMethods.unlikeImage,
  trashImage: interactionsGalleryMethods.trashImage,
  restoreImage: interactionsGalleryMethods.restoreImage,
  getStatus: adminGalleryMethods.getStatus,
  getScanProgress: adminGalleryMethods.getScanProgress,
  getAdminScanProgress: adminGalleryMethods.getAdminScanProgress,
  getStats: adminGalleryMethods.getStats,
  setDefaultHomeFeedMode: adminGalleryMethods.setDefaultHomeFeedMode,
  setDefaultLocale: adminGalleryMethods.setDefaultLocale,
  setDefaultReelsFeedMode: adminGalleryMethods.setDefaultReelsFeedMode,
  setDefaultFolderImageOrder: adminGalleryMethods.setDefaultFolderImageOrder,
  setSharePublicBaseUrl: adminGalleryMethods.setSharePublicBaseUrl,
  setVideoPlaybackQuality: adminGalleryMethods.setVideoPlaybackQuality,
  setVideoPlaybackMode: adminGalleryMethods.setVideoPlaybackMode,
  setNestedFolderTitleFormat: adminGalleryMethods.setNestedFolderTitleFormat,
  setTreatStoriesAsFolders: adminGalleryMethods.setTreatStoriesAsFolders,
  setExcludedFolders: adminGalleryMethods.setExcludedFolders,
  getOriginalMediaFile: adminGalleryMethods.getOriginalMediaFile,
  getOriginalImagePath: adminGalleryMethods.getOriginalImagePath,
  deleteImage: adminGalleryMethods.deleteImage,
  deleteFolder: adminGalleryMethods.deleteFolder,
  setTreatCarouselsAsFolders: adminGalleryMethods.setTreatCarouselsAsFolders,
  setCarouselsMigrationDecision: adminGalleryMethods.setCarouselsMigrationDecision
};
